//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidenceCapture.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class DisplaySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DisplaySettings defaultInstance = ((DisplaySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DisplaySettings())));
        
        public static DisplaySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public double DefaultDisplayWidth {
            get {
                return ((double)(this["DefaultDisplayWidth"]));
            }
            set {
                this["DefaultDisplayWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public double DefaultDisplayHeight {
            get {
                return ((double)(this["DefaultDisplayHeight"]));
            }
            set {
                this["DefaultDisplayHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultDisplayIsNormal {
            get {
                return ((bool)(this["DefaultDisplayIsNormal"]));
            }
            set {
                this["DefaultDisplayIsNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DefaultDisplayX {
            get {
                return ((double)(this["DefaultDisplayX"]));
            }
            set {
                this["DefaultDisplayX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DefaultDisplayY {
            get {
                return ((double)(this["DefaultDisplayY"]));
            }
            set {
                this["DefaultDisplayY"] = value;
            }
        }
    }
}
