//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidenceCapture.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvidenceCapture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   グループの追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddGroupToolTip {
            get {
                return ResourceManager.GetString("AddGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppliactionSettingControlTooltip {
            get {
                return ResourceManager.GetString("AppliactionSettingControlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションログフォルダを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplogTooltip {
            get {
                return ResourceManager.GetString("ApplogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EvidenceCapture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動リサイズを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoResizeToolTip {
            get {
                return ResourceManager.GetString("AutoResizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カメラが一つも見当たりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraNotFound {
            get {
                return ResourceManager.GetString("CameraNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeButton {
            get {
                return ResourceManager.GetString("ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高さ変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixHeight {
            get {
                return ResourceManager.GetString("FixHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幅変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixWidth {
            get {
                return ResourceManager.GetString("FixWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatExcel {
            get {
                return ResourceManager.GetString("FormatExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatHTML {
            get {
                return ResourceManager.GetString("FormatHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatPDF {
            get {
                return ResourceManager.GetString("FormatPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ表現 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupPattern {
            get {
                return ResourceManager.GetString("GroupPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更後のグループを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupRenameCaption {
            get {
                return ResourceManager.GetString("GroupRenameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下位グループをリセットする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupRenameOption {
            get {
                return ResourceManager.GetString("GroupRenameOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ名の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupRenameTitle {
            get {
                return ResourceManager.GetString("GroupRenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハイライト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HIghlightTooltip {
            get {
                return ResourceManager.GetString("HIghlightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bmp型式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFormatBmp {
            get {
                return ResourceManager.GetString("ImageFormatBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jpeg型式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFormatJpg {
            get {
                return ResourceManager.GetString("ImageFormatJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   png型式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFormatPng {
            get {
                return ResourceManager.GetString("ImageFormatPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スナップショット書式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageSettingExpander {
            get {
                return ResourceManager.GetString("ImageSettingExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウインドウも含める に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsWindowCapture {
            get {
                return ResourceManager.GetString("IsWindowCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクティブウインドウキャプチャ範囲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsWindowCaptureLabel {
            get {
                return ResourceManager.GetString("IsWindowCaptureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーショートカット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeySettingExpander {
            get {
                return ResourceManager.GetString("KeySettingExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクティブウインドウキャプチャー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyShortCutApplicationCap {
            get {
                return ResourceManager.GetString("KeyShortCutApplicationCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カメラキャプチャー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyShortCutCameraCap {
            get {
                return ResourceManager.GetString("KeyShortCutCameraCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ追加(レベル1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyShortCutG1 {
            get {
                return ResourceManager.GetString("KeyShortCutG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ追加(レベル2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyShortCutG2 {
            get {
                return ResourceManager.GetString("KeyShortCutG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ追加(レベル3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyShortCutG3 {
            get {
                return ResourceManager.GetString("KeyShortCutG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンキャプチャー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyShortCutScreenCap {
            get {
                return ResourceManager.GetString("KeyShortCutScreenCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LaunchDirButton {
            get {
                return ResourceManager.GetString("LaunchDirButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを起動する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LaunchFileButton {
            get {
                return ResourceManager.GetString("LaunchFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レポートを出力する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LaunchReportDialogToolTip {
            get {
                return ResourceManager.GetString("LaunchReportDialogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスキング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaskTooltip {
            get {
                return ResourceManager.GetString("MaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スナップショットキャプチャ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperateControlTooltip {
            get {
                return ResourceManager.GetString("OperateControlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レポート出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReportDialogTitle {
            get {
                return ResourceManager.GetString("ReportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レポートを出力しました。
        ///出力先={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReportFinishCaption {
            get {
                return ResourceManager.GetString("ReportFinishCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レポート出力が完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReportFinishTitle {
            get {
                return ResourceManager.GetString("ReportFinishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するフォーマットを選択し、作成ボタンをおしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFormatCaption {
            get {
                return ResourceManager.GetString("SelectFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先フォルダの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetFolderToolTip {
            get {
                return ResourceManager.GetString("SetFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リサイズのデフォルト(高さ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SnapShotFormatHeight {
            get {
                return ResourceManager.GetString("SnapShotFormatHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力フォーマット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SnapShotFormatOutFormat {
            get {
                return ResourceManager.GetString("SnapShotFormatOutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リサイズのデフォルト(幅) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SnapShotFormatWidth {
            get {
                return ResourceManager.GetString("SnapShotFormatWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トリミング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrimTooltip {
            get {
                return ResourceManager.GetString("TrimTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Webカメラが認識できませんでした。
        ///カメラのキャプチャは利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebCamNotFound {
            get {
                return ResourceManager.GetString("WebCamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Webカメラの設定と確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebCamSettingTooltip {
            get {
                return ResourceManager.GetString("WebCamSettingTooltip", resourceCulture);
            }
        }
    }
}
